// Scans plugins.local/ for third-party widgets and (re)generates
// src/plugins/external.generated.ts, which the registry merges into `widgets`.
// Convention: each external plugin lives in plugins.local/<name>/plugin.tsx and
// exports `export const plugin: Widget`. Runs on build (prebuild) and on demand
// via `npm run plugins:scan`. Safe when the folder is missing/empty.

import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const dir = join(root, "plugins.local");
const outFile = join(root, "src", "plugins", "external.generated.ts");

const header =
  "// AUTO-GENERATED by scripts/scan-plugins.mjs — do not edit by hand.\n" +
  "// Refresh with `npm run plugins:scan` (also runs automatically before build).\n" +
  'import type { Widget } from "./registry";\n\n';

const imports = [];
const idents = [];

if (existsSync(dir)) {
  const names = readdirSync(dir)
    .filter((n) => {
      try {
        return statSync(join(dir, n)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort();
  names.forEach((name) => {
    const hasTsx = existsSync(join(dir, name, "plugin.tsx"));
    const hasTs = existsSync(join(dir, name, "plugin.ts"));
    if (!hasTsx && !hasTs) return;
    const ident = `ext_${name.replace(/[^A-Za-z0-9_]/g, "_")}`;
    imports.push(`import { plugin as ${ident} } from "../../plugins.local/${name}/plugin";`);
    idents.push(ident);
  });
}

const body =
  (imports.length ? imports.join("\n") + "\n\n" : "") +
  `export const externalWidgets: Widget[] = [${idents.join(", ")}];\n`;

writeFileSync(outFile, header + body);
console.log(`scan-plugins: wrote ${idents.length} external plugin(s) to src/plugins/external.generated.ts`);
