// AUTO-GENERATED by scripts/scan-plugins.mjs — do not edit by hand.
// Refresh with `npm run plugins:scan` (also runs automatically before build).
import type { Widget } from "./registry";

export const externalWidgets: Widget[] = [];
