// AUTO-GENERATED by scripts/scan-plugins.mjs — do not edit by hand.
// Refresh with `npm run plugins:scan` (also runs automatically before build).
import type { Widget } from "./registry";

import { plugin as ext_reference } from "../../plugins.local/reference/plugin";

export const externalWidgets: Widget[] = [ext_reference];
